name: flutter_audio_games_maps
description: "A library for making maps in audio games."
version: 0.0.1
repository: https://github.com/chrisnorman7/flutter_audio_games_maps

environment:
  sdk: '>=3.3.0-174.2.beta <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  backstreets_widgets: ^0.9.0
  dart_synthizer: ^0.11.2
  flutter:
    sdk: flutter
  flutter_audio_games: ^0.10.1
  flutter_synthizer: ^0.4.1

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
